bp/urls.py
from django.urls import path
from . import views

app_name = 'bp'
urlpatterns = [
    path('', views.index, name='index'),
    path('sample', views.sample),
    path('province', views.province),
    path('allcounty', views.allcounty),
]

wps/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^wpsa/', include('wpsa.urls')),
    url(r'^v1/common/', include('bp.urls')),
    url(r'^admin/', admin.site.urls),
]

wpsa/urls.py
from django.conf import settings
#from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.contrib.staticfiles.urls import static
from django.conf.urls import url
from . import views

app_name = 'wpsa'
urlpatterns = [
	url(r'^$', views.IndexView.as_view(), name='index'),
	url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
	url(r'^register_wp/$', views.register_wp, name='register_wp'),
	url(r'^(?P<wp_id>[0-9]+)/addcomment/$', views.addcomment, name='addcomment')
]

#urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

bp/models.py
from django.db import models

class Province(models.Model):
    class Meta:
       managed = False
       db_table = "province"
    name = models.CharField(max_length=50)

class County(models.Model):
    class Meta:
       managed = False
       db_table = "county"
    name = models.CharField(max_length=50)
    province = models.IntegerField()

wpsa/models.py
from __future__ import unicode_literals
from django.db import models
from django.utils import timezone

WS_TYPE = (
	(0, 'Office'),
	(1, 'Shopping'),
	(2, 'Home'),
)

SEXT_TYPE = (
	(0, 'Male'),
	(1, 'Female')
)

class UserProfile(models.Model):
    user_name = models.CharField(max_length=50)
    name = models.CharField(max_length=30)
    email = models.CharField(max_length=50)
    mobile = models.CharField(max_length=30)
    tel = models.CharField(max_length=50)
    sex = models.IntegerField(choices=SEXT_TYPE)

class Workplace(models.Model):
	area = models.IntegerField(default=0)
	ws_type = models.IntegerField(choices=WS_TYPE)
	title = models.CharField(max_length=500)
	description = models.CharField(max_length=8000)
	price = models.DecimalField(default=0, max_digits=10,decimal_places=2)
	start_date = models.DateTimeField('start of sharing')
	end_date = models.DateTimeField('end of sharing')
	register_date = models.DateTimeField('register this ws in the system')
	expire_date = models.DateTimeField('when advertising of this ws ends')
	published = models.BooleanField('is published?')
	province = models.CharField(max_length=50)
	city = models.CharField(max_length=50)
	address = models.CharField(max_length=200)
	map_location = models.CharField(max_length=200, help_text='Longitude, Latitude')
	image = models.FileField(upload_to='%Y/%m/%d/', null=True, blank=True)
	advertiser = models.ForeignKey(UserProfile, on_delete=models.CASCADE)
	def active_wp(self):
		return self.start_date >= timezone.now() - datetime.timedelta(days=30)
	def __str__(self):
		return self.province + ", " + self.city

class Comment(models.Model):
	create_date = models.DateTimeField('when comment is created')
	published = models.BooleanField('is published?')
	ip = models.CharField(max_length=40)
	spam = models.BooleanField('is it spam?')
	commenter_email = models.CharField(max_length=80)
	commenter_name = models.CharField(max_length=80)
	body = models.CharField(max_length=8000)
	commenter = models.ForeignKey(UserProfile, on_delete=models.CASCADE)
	workplace = models.ForeignKey(Workplace, on_delete=models.CASCADE)

wpsa/forms.py
from django import forms
from django.forms import ModelForm
from .models import Workplace

class NameForm(forms.Form):
    your_name = forms.CharField(label='Your Name', max_length=100)
    
class ContactForm(forms.Form):
    subject = forms.CharField(max_length=100)
    message = forms.CharField(widget=forms.Textarea)
    sender = forms.EmailField()
    cc_myself = forms.BooleanField(required=False)
    
class WorkplaceForm(ModelForm):
    class Meta:
        model = Workplace
        fields = ['title','province','city','price', 'ws_type', 'area','address','description', 'image']
        #article = Article.objects.get(pk=1)
        #form = ArticleForm(instance=article)

bp/views.py
from django.shortcuts import render
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, Http404, HttpResponseRedirect
from django.template import loader
from django.urls import reverse
from django.utils import timezone
from django.views import generic
from django.core.mail import send_mail
import json
from django.http import JsonResponse
from .models import Province, County


def index(request):
    return HttpResponse("Hello World, it is the index")


def sample(request):
    response_data = {}
    response_data['name'] = 'ON'
    response_data['Capital'] = 'Toronto123'
    return JsonResponse(response_data)


def province(request):
    pro = Province.objects.all().order_by('name').values()
    ret = {"province": list(pro)}
    return JsonResponse(ret)


def allcounty(request):
    provinces = Province.objects.all().order_by('name').values()
    counties = County.objects.all().order_by('name').values()
    ret = {
        "validity": 1440,
        "provinces": list(provinces),
        "counties": list(counties)
    }
    return JsonResponse(ret)

wpsa/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, Http404, HttpResponseRedirect
from .models import Workplace, Comment
from django.template import loader
from django.urls import reverse
from django.utils import timezone
from django.views import generic
from .forms import NameForm, WorkplaceForm
from django.core.mail import send_mail

class IndexView(generic.ListView):
	template_name = 'wpsa/index.html'
	context_object_name = 'active_wp'
	def get_queryset(self):
	   return Workplace.objects.order_by('-start_date')[:50]

class DetailView(generic.DetailView):
	model = Workplace
	template_name = 'wpsa/detail.html'

def addcomment(request, wp_id):
	wp = get_object_or_404(Workplace, pk=wp_id)
	c = Comment(body = request.POST['body'], create_date = timezone.now(), published=1, spam=1, commenter_id=-1, workplace_id=wp_id)
	c.save()
	return HttpResponseRedirect(reverse('wpsa:detail', args=(wp_id,)))

def get_name(request):
    #if this is a POST request we need to process the form data
    if request.method == 'POST':
        #create a from instance and populate it with data from the request:
        form = NameForm(request.POST)
        #check whether it's valid:
        if form.is_valid():
            #process the data in form.cleaned_data as required
            #...
            #redirect to a new URL:
            return HttpResponseRedirect('/thanks/')
        
        #if a GET (or any other method) we'll create a blank form
        else:
            form = NameForm()
        
        return render(request, 'name.html', {'form': form})

def contact_from(request):
    #if this is a POST request we need to process the form data
    if request.method == 'POST':
        #create a from instance and populate it with data from the request:
        form = ContactForm(request.POST)
        #check whether it's valid:
        if form.is_valid():
            #process the data in form.cleaned_data as required
            #...
            #redirect to a new URL:
            subject = form.cleaned_data['subject']
            message = form.cleaned_data['message']
            sender = form.cleaned_data['sender']
            cc_myself = form.cleaned_data['cc_myself']
            
            recipients = ['info@example.com']
            
            if cc_myself:
                recipients.append(sender)
                
            send_mail(subject, message, sender, recipients)            
            return HttpResponseRedirect('/thanks/')
        
        #if a GET (or any other method) we'll create a blank form
        else:
            form = NameForm()
        
        return render(request, 'name.html', {'form': form})

def register_wp(request):
    if request.method == 'POST':
        form = WorkplaceForm(request.POST, request.FILES)
        if form.is_valid():
            time_now = timezone.now()
            wp = form.save(commit=False)
            wp.create_date = time_now 
            wp.start_date = time_now
            wp.end_date = time_now
            wp.register_date = time_now
            wp.expire_date = time_now
            wp.published = 1
            wp.advertiser_id = 0
            wp.save()
        return HttpResponseRedirect(reverse('wpsa:detail', args=(wp.id,)))        
    else: #GET or anything else
        form = WorkplaceForm()
        return render(request, 'wpsa/register_wp.html', {'form': form})

wpsa/templates/wpsa/base.html
<!DOCTYPE HTML>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="A sample application for learning Django">
    <meta name="author" content="wps application">
    <link rel="icon" href="../../favicon.ico">

    <title>WPS - {% block title %}{% endblock %}</title>

{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'wpsa/bootstrap/css/bootstrap.min.css' %}" />
<link rel="stylesheet" type="text/css" href="{% static 'wpsa/style.css' %}" />
  </head>

  <body role="document">

    <!-- Fixed navbar -->
    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/wpsa/">WPS</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li class="active"><a href="/wpsa/">Home</a></li>
            <li><a href="/wpsa/register_wp/">Register</a></li>            
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><a href="#">Action</a></li>
                <li><a href="#">Another action</a></li>
                <li><a href="#">Something else here</a></li>
                <li role="separator" class="divider"></li>
                <li class="dropdown-header">Nav header</li>
                <li><a href="#">Separated link</a></li>
                <li><a href="#">One more separated link</a></li>
              </ul>
            </li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>
    <div class="container" role="main">
	        {% block body_block %}
			<p> No content </p>
			{% endblock %}
    </div> <!-- /container -->
	<script src="{% static 'wpsa/jquery-2.2.3.min.js' %}"></script>
	<script src="{% static 'wpsa/bootstrap/js/bootstrap.min.js' %}"></script>
  </body>
</html>

wpsa/templates/wpsa/detail.html
{% extends 'wpsa/base.html' %}
{% block title %} detail {% endblock %}
{% block body_block %}
<br/>
<a href="/wpsa">Back to list...</a>

<h1>{{workplace}}</h1>
<ul>
{% for comment in workplace.comment_set.all %}
	<li>{{comment.body}}</li>
{% endfor %}
</ul>

{% if error_message %}<p><strong>{{error_message}}</strong></p>{% endif %}

<form action="{% url 'wpsa:addcomment' workplace.id %}" method="post">
	{% csrf_token %}
	<input type="text" name="body" id="body"/>
	<input type="submit" value="Add Comment"/>
</form>
{% endblock %}

wpsa/templates/wpsa/index.html
{% extends 'wpsa/base.html' %}
{% block title %} list {% endblock %}
{% block body_block %}
      <!-- Main jumbotron for a primary marketing message or call to action -->
      <div class="jumbotron">
        <h1>Welcome WPS</h1>
        <p>This is a sample project to learn Django/Python</p>
      </div>

{% if active_wp %}
	{% for wp in active_wp %}
<div class="row">
    <div class="col-md-3 col-sm-2 col-xs-6">        
        <a class="thumbnail" href="{% url 'wpsa:detail' wp.id %}">
            {% if wp.image %} <!-- image is empty or null -->
            <img src=uploads/{{wp.image}}>            
            {% else %}
            <img src="http://placehold.it/300x300&text=NO IMAGE">
            {% endif %}
            </a>                    
    </div>                    
    <div class="col-md-8 col-sm-5 col-xs-4">
        <h3>{{wp.title}}</h3>
		{% if wp.ws_type == 0 %}
		<img src="/static/wpsa/images/office.jpg" class="ico"/>
		{% elif wp.ws_type == 1 %}
		<img src="/static/wpsa/images/shopping.png" class="ico"/>
		{% elif wp.ws_type == 2 %}
		<img src="/static/wpsa/images/home.png" class="ico"/>
		{% else %}
		<img src="/static/wpsa/images/unknown.gif" class="ico"/>
		{% endif %}
        {{wp.city}}, {{wp.province}}
        <br/>
        {{wp.area}} <span class="gray">sqft</span>, {{wp.address}}
        <br/>
        {{wp.start_date|date:'Y-m-d'}}
        <br/>
        <p>
	        {{wp.description}}
        </p>
	</div>
    <div class="col-md-1 col-sm-1 col-xs-1 align-right">
        <span class="price"> ${{wp.price}} </span>
    </div>
</div>
	{% endfor %}
{% else %}
	<p>
		No Workplace is defined
	</p>
{% endif %}
{% endblock %}

wpsa/templates/wpsa/name.html
{% extends 'wpsa/base.html' %}
{% block title %} name {% endblock %}
{% block body_block %}
<form action="/your-name/" method="post">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="Submit" />
</form>
{% endblock %}

wpsa/templates/wpsa/register_wp.html
{% extends 'wpsa/base.html' %}
{% block body_block %}
{% block title %} Register a Workplace {% endblock %}
<h1>Register a Workplace</h1>
<a href="/wpsa">Back to list...</a>
<form action="/wpsa/register_wp/" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Submit" />
</form>
{% endblock %}